name: deploy-container

on:
  push:
    branches:
      - '*'
    paths:
      - '**'

defaults:
  run:
    working-directory: MarketingApp/Container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:: 'us-east-2'

      - name: Execute AWS CLI Command
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/Container/latest